### ISSUE TITLE
Timex dependency excludes latest versions

### ISSUE THREAD

**Issue by deepankar-j** [dbernheisel/date_time_parser#9] opened 2023-05-11 13:24 UTC
The dependency of timex >= 3.2.1 and <= 3.7.2 prevents my app from being able to upgrade timex to the latest version.  Could you please update the dependency to allow the latest version of times, 3.7.11?

**Comment by dbernheisel** [comment] 2023-05-11 13:34
Duplicate of #5

**Comment by dbernheisel** [comment] 2023-05-11 13:34
Can you try the main branch and see if that helps? It drops the Timex dependency.

**Closed by dbernheisel** 2023-05-11 13:34 UTC

**Comment by dbernheisel** [comment] 2023-12-06 19:40
This has been released in 1.2.0
